[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/skerkour/crypto42-rs"]
git = "https://github.com/skerkour/crypto42-rs"
replace-with = "vendored-sources"

[source."https://github.com/skerkour/stdx"]
git = "https://github.com/skerkour/stdx"
branch = "tokio02"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
